# Generated by Django 4.2.3 on 2023-07-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='digests.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostToDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digests.digest')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digests.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='digests.subscription'),
        ),
        migrations.AddField(
            model_name='digest',
            name='posts',
            field=models.ManyToManyField(related_name='digest', through='digests.PostToDigest', to='digests.post'),
        ),
        migrations.AddField(
            model_name='digest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digests.user'),
        ),
    ]
