# Generated by Django 4.2.3 on 2023-07-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_alter_subscription_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='month',
            new_name='rating',
        ),
    ]
